//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKH.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ServiceID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public double Total { get; set; }
        public bool IsDelete { get; set; }
        public double Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
    }
}
